spring:
  datasource:
    username: developer
    password: super_secret_password
    url: jdbc:postgresql://localhost:5432/db_portal
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        use_sql_comments: true
        highlight_sql: true
        default_schema: portal_schema
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 10
          fetch_size: 50
          time_zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: 60s
  main:
    lazy-initialization: false
    banner-mode: console
  mail:
    username: 
    password: 
    port: 587
    host: smtp.mail.ru
    test-connection: false
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api/v1
  tomcat:
    accesslog:
      enabled: false

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      springframework: INFO

debug: false
